# 1. Utiliser l'image officielle PHP avec le serveur Apache pré-configuré
FROM php:8.2-apache

# 2. Copier notre fichier index.php local vers le dossier web d'Apache dans le conteneur
COPY index.php /var/www/html/

# 3. Informer que le conteneur écoute sur le port 80 (Demande de l'énoncé)
EXPOSE 80